version: '3'
services:
  django_app:
    #image: django_app:latest
    build: .
    container_name: django_app
    restart: always
    links:
      - django_app_db
      - django_app_redis
    ports:
      - "80:8000"
  #  volumes: 
  #    - ./Swyft/:/code
 

  django_app_db:
    image: mysql:5.7
    restart: always
    container_name: django_app_db
    ports:
      - "3306"
    volumes:
      - ./data/django_app_mysql_data:/var/lib/mysql

    environment:
      - MYSQL_ROOT_PASSWORD=Trail@123
      - MYSQL_DATABASE=trail_project
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin


#django_app_nginx:
#  image: nginx:latest
#  restart: always
#  container_name: django_app_nginx
#  links:
#    - django_app:uwsgi
#  ports:
#    - "8080:80"
#  volumes:
#    - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  django_app_redis:
    image: redis:latest
    container_name: django_app_redis
    ports:
      - "6379"
