# Generated by Django 2.2.6 on 2021-05-07 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
