# Generated by Django 2.2.6 on 2021-05-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trial', '0002_delete_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('model', models.TextField()),
                ('make', models.TextField()),
                ('price', models.FloatField()),
                ('year', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
